## Introdução

**O YouTube é um dos maiores repositórios de conteúdo audiovisual e interação social do mundo**, gerando diariamente milhões de visualizações, comentários e avaliações. Essa massa de dados desperta interesse por ser produzida de forma orgânica, refletindo tanto eventos quanto as reações dos usuários a eles.

Nesse contexto, as relações presentes nesse ecossistema passaram a ser objeto de investigação da comunidade acadêmica. Entre os estudos pioneiros, *Chatzopoulou et al. (2010)*, analisando aproximadamente 37 milhões de registros, demonstraram **forte correlação entre visualizações, comentários, curtidas e favoritos**, identificando padrões estruturais de engajamento na plataforma.

Posteriormente, *Hoiles et al. (2016)* ampliaram essa perspectiva ao mostrar que **fatores como visualizações no primeiro dia, número de inscritos e estratégias de otimização pós-publicação** — incluindo títulos, miniaturas e tags — figuram entre os principais preditores de popularidade.

Em outra abordagem, *Yang et al. (2022)* observaram que **vídeos mais curtos e sinalizações sociais, como curtidas, apresentam associação positiva com diferentes formas de engajamento**, embora a análise tenha sido limitada a um único canal de divulgação científica.

Mais recentemente, *Giankos et al. (2025)* verificaram, em canais de pesca, que **a otimização de palavras-chave nos títulos exerce papel relevante na visibilidade dos vídeos**, enquanto características estruturais, como a duração, não apresentaram influência significativa sobre o número de visualizações.

**Contudo, esses trabalhos concentram-se predominantemente em métricas estruturais e metadados**, deixando em segundo plano as informações semânticas presentes nos títulos, descrições e comentários. Como consequência, **permanece pouco explorada a possibilidade de identificar categorias emergentes, padrões sociais e relações temáticas** que não são explicitamente representadas pelas classificações oficiais da plataforma.

In [1]:
## Imports de bibliotécas e classes utilitárias

from __future__ import annotations
from typing import Any

from IPython.display import display, Markdown

import sys
from datetime import datetime, timezone
from pathlib import Path
import pandas as pd
import numpy as np

ROOT: Path = Path.cwd().parent
sys.path.append(str(ROOT))

import src.core.util_examplification as examplification
import src.core.util as util
import src.core.view as view

In [2]:
## Carregamento de dados
BASE_DIR = Path("../data/raw")

datasets: dict[str, pd.DataFrame] = util.load_datasets(BASE_DIR)

videos_df: pd.DataFrame = datasets["videos"]
comments_df: pd.DataFrame = datasets["comments"]
channels_df: pd.DataFrame = datasets["channels"]

view.box(
    f"""
    <b>Dataset carregado</b><br>
    Vídeos: {len(videos_df):,}<br>
    Comentários: {len(comments_df):,}<br>
    Caanais: {len(channels_df):,}
    """,
)

In [3]:

## display de uma parcelas dos dados
# from ydata_profiling import ProfileReport
# profile = ProfileReport(videos_df, title="Dataset Exploratory Analysis Report")
# profile.to_file("data_video_report.html")
# profile = ProfileReport(comments_df, title="Dataset Exploratory Analysis Report")
# profile.to_file("data_comments_report.html")
# profile = ProfileReport(channels_df, title="Dataset Exploratory Analysis Report")
# profile.to_file("data_channel_report.html")
view.printf("# visão geral e estrutura do dataset")
view.printf("## amostra dos dados (primeiras 5 linhas)")
display(videos_df.head())

display(Markdown("---"))

view.printf("##  rsumo estatístico (variáveis nméricas)")
display(videos_df.describe()) 

if videos_df.select_dtypes(include=['object']).shape[1] > 0:
    view.printf("## resumo estatístico (variáveis categóricas)")
    display(videos_df.describe())

# visão geral e estrutura do dataset

## amostra dos dados (primeiras 5 linhas)

,video_id,title,channel_title,channel_id,published_at,category_id,thumbnail,view_count,like_count,comment_count,tags,duration,source_file,source_path,collection_id,country
0,CQeTZ1fCJFw,JOGO COMPLETO: BRASIL X EGITO | AMISTOSO DA SE...,ge tv,UCgCKagVhzGnZcuP9bSMgMCg,2026-06-07T01:11:37Z,17,https://i.ytimg.com/vi/CQeTZ1fCJFw/default.jpg,25801556,654555.0,320.0,"['seleção brasileira', 'seleção', 'seleção bra...",PT4H53M23S,youtube_videos_br.csv,../data/raw/output_220808062026/id_17/youtube_...,id_17,br
1,DaP0oU9ecHY,QUAL É O JOGADOR ??? #shorts #copadomundo,Anninha,UC7-xgj9qGUt4qL_2zcR7Clg,2026-06-06T15:45:36Z,24,https://i.ytimg.com/vi/DaP0oU9ecHY/default.jpg,4960877,273281.0,380.0,[],PT39S,youtube_videos_br.csv,../data/raw/output_220808062026/id_17/youtube_...,id_17,br
2,Ze_90XKWJ3w,O álbum do Mundial mal lançou e já deu problema,Explora Mundo,UCR-Z99fGpj3HvDN--tHaFgQ,2026-06-05T18:45:21Z,22,https://i.ytimg.com/vi/Ze_90XKWJ3w/default.jpg,4319330,132798.0,454.0,"['album do mundial', 'álbum da copa', 'figurin...",PT40S,youtube_videos_br.csv,../data/raw/output_220808062026/id_17/youtube_...,id_17,br
3,uDEU_EwMrsw,Brasil x Egito Vai Dar Bom?,Studio CI Futebol,UCpZWE6XLj-VxGgZRzDYgktw,2026-06-05T11:17:45Z,17,https://i.ytimg.com/vi/uDEU_EwMrsw/default.jpg,3744098,100894.0,2167.0,"['brasil x egito vai dar bom?', 'copa do mundo...",PT15S,youtube_videos_br.csv,../data/raw/output_220808062026/id_17/youtube_...,id_17,br
4,Mh90m0c_x2s,OLÍVIA FEZ 4 MESES ❤️,Pai da Mia,UCB4Hanh4eBS0nyIj--_xY_Q,2026-06-04T18:44:12Z,22,https://i.ytimg.com/vi/Mh90m0c_x2s/default.jpg,7109630,172670.0,6771.0,[],PT34S,youtube_videos_br.csv,../data/raw/output_220808062026/id_17/youtube_...,id_17,br

---

##  rsumo estatístico (variáveis nméricas)

       category_id    view_count    like_count  comment_count
count  3597.000000  3.597000e+03  3.476000e+03    3594.000000
mean     21.476508  2.507019e+06  7.090941e+04     601.702282
std       4.031000  8.208102e+06  1.550259e+05    1537.235275
min       1.000000  6.857000e+03  1.170000e+02       0.000000
25%      20.000000  2.451840e+05  9.873750e+03      85.000000
50%      22.000000  7.956540e+05  3.266650e+04     230.000000
75%      24.000000  1.800094e+06  7.489300e+04     558.750000
max      29.000000  1.714957e+08  2.838595e+06   23326.000000

## resumo estatístico (variáveis categóricas)

       category_id    view_count    like_count  comment_count
count  3597.000000  3.597000e+03  3.476000e+03    3594.000000
mean     21.476508  2.507019e+06  7.090941e+04     601.702282
std       4.031000  8.208102e+06  1.550259e+05    1537.235275
min       1.000000  6.857000e+03  1.170000e+02       0.000000
25%      20.000000  2.451840e+05  9.873750e+03      85.000000
50%      22.000000  7.956540e+05  3.266650e+04     230.000000
75%      24.000000  1.800094e+06  7.489300e+04     558.750000
max      29.000000  1.714957e+08  2.838595e+06   23326.000000

In [ ]:
view.printf(f"Videos: {len(videos_df)}")
df: pd.DataFrame = videos_df.drop_duplicates(subset=["video_id"])
view.printf(f"**Videos: {len(df)}!** com {len(videos_df)-len(df)} duplicados")

Videos: 3597

**Videos: 1354!** com 2243 duplicados

In [5]:
df["published_at"] = pd.to_datetime(df["published_at"], utc=True, errors="coerce")

for col in ["view_count", "like_count", "comment_count"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

for col in ["video_id", "title", "channel_title", "channel_id", "thumbnail",
            "tags", "duration", "source_file", "source_path", "collection_id", "country"]:
    df[col] = df[col].astype("string").str.strip()

/tmp/ipykernel_93620/252455176.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["published_at"] = pd.to_datetime(df["published_at"], utc=True, errors="coerce")
/tmp/ipykernel_93620/252455176.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_93620/252455176.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype("string").str.strip()
/tmp/ipykernel_93620/252455176.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype("string").str.strip()
/tmp/ipykernel_93620/252455176.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype("string").str.strip()
/tmp/ipykernel_93620/252455176.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype("string").str.strip()
/tmp/ipykernel_93620/252455176.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype("string").str.strip()
/tmp/ipykernel_93620/252455176.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype("string").str.strip()
/tmp/ipykernel_93620/252455176.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype("string").str.strip()
/tmp/ipykernel_93620/252455176.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype("string").str.strip()
/tmp/ipykernel_93620/252455176.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype("string").str.strip()
/tmp/ipykernel_93620/252455176.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype("string").str.strip()
/tmp/ipykernel_93620/252455176.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype("string").str.strip()

In [6]:
def duration_to_seconds(x):
    if pd.isna(x):
        return np.nan
    try:
        return int(isodate.parse_duration(x).total_seconds())
    except (isodate.isoerror.ISO8601Error, ValueError):
        return np.nan

df["duration_seconds"] = df["duration"].apply(duration_to_seconds)
df["is_short"] = df["duration_seconds"] <= 60

NameError: name 'isodate' is not defined

In [ ]:
def parse_tags(x):
    if pd.isna(x):
        return []
    if isinstance(x, list):
        return x
    try:
        return [t.strip().lower() for t in ast.literal_eval(x)]
    except:
        return [t.strip().lower() for t in str(x).strip("[]").split(",") if t.strip()]


df["tags_list"] = df["tags"].apply(parse_tags)
df["tags_n"] = df["tags_list"].apply(len)

In [ ]:
# df["like_count_missing"] = df["like_count"].isna().astype(int)
# df["comment_count_missing"] = df["comment_count"].isna().astype(int)
df["title_len"] = df["title"].str.len()
df["title_words"] = df["title"].str.split().apply(len)

df["log_view_count"] = np.log1p(df["view_count"])
df["log_like_count"] = np.log1p(df["like_count"])
df["log_comment_count"] = np.log1p(df["comment_count"])

df["engagement_rate"] = (df["like_count"] + df["comment_count"]) / df["view_count"]
df["likes_per_view"] = df["like_count"] / df["view_count"]
df["comments_per_view"] = df["comment_count"] / df["view_count"]

In [ ]:

LIKE_WEIGHT = 2
COMMENT_WEIGHT = 5
display(df.nlargest(10, "view_count")[
    ["title", "country", "view_count", "published_at","duration_seconds"]
])
view.printf("---")
view.printf("### Problema encontrado... os videos curtos, ou 'shorts' são máquinas de outliers, e säo extremamente pobres em engajamento")
view.printf("### Sua natureza pode quebrar a precisão do estudo")

shorts: pd.Series = df[df["duration_seconds"] <= 240]
view.printf(f"### Total de videos: {len(df)}")
view.printf(f"### Total de videos não shorts {len(df)-len(shorts)}")
view.printf(f"### Total de shorts: {len(shorts)}")
view.printf("---")

df_long: pd.Series = df[df["duration_seconds"] > 240]

df_long["engagement_rate"] = np.where(
    df_long["view_count"].gt(0),
    (
        df_long["like_count"]* LIKE_WEIGHT +
        df_long["comment_count"]* COMMENT_WEIGHT
    ) / df_long["view_count"],
    np.nan
)
examplification.plot_engagement_rate_example(df, LIKE_WEIGHT, COMMENT_WEIGHT)
df_long["likes_per_view"] = np.where(
    df_long["view_count"] > 0,
    df_long["like_count"] / df_long["view_count"],
    np.nan
)

df_long["comments_per_view"] = np.where(
    df_long["view_count"] > 0,
    df_long["comment_count"] / df_long["view_count"],
    np.nan
)
display(df_long.nlargest(10, "view_count")[
    ["title", "country", "view_count", "published_at","duration_seconds"]
])
df = df_long.copy()

In [ ]:
# métricas de engajamento, dá para ter um indicadores de sucesso com
# essas métricas, pois utiliza como critério para ter um comentário ou like é necessário ter tido ao menos uma view
# e engajar significa levar outro individuo a tomar uma acão, logo a view seria a base para os demais, näo há os
# demais sem visualizacão

# df["engagement_rate"] = np.where(
#     df["view_count"] > 0,
#     (df["like_count"] + df["comment_count"]) / df["view_count"],
#     np.nan
# )


# cria uma métrica personalizada chamada taxa de engajamento, dando 
# pesos diferentes para curtidas e comentários.
# df["engagement_rate"] = np.where(
#     df["view_count"].gt(0),
#     (
#         df["like_count"]* LIKE_WEIGHT +
#         df["comment_count"]* COMMENT_WEIGHT
#     ) / df["view_count"],
#     np.nan
# )
# examplification.plot_engagement_rate_example(df, LIKE_WEIGHT, COMMENT_WEIGHT)
# df["likes_per_view"] = np.where(
#     df["view_count"] > 0,
#     df["like_count"] / df["view_count"],
#     np.nan
# )

# df["comments_per_view"] = np.where(
#     df["view_count"] > 0,
#     df["comment_count"] / df["view_count"],
#     np.nan
# )

In [ ]:

view.printf(f"""<h3>
       Em dados de redes sociais e YouTube, as distribuições costumam ser extremamente assimétricas.
       O maior valor domina completamente a escala. Criando uma discrepancia enorme na comparacao
       Principalmente neste cenário onde 
       </h3>
       """
       )
examplification.plot_logn1_example()

df["log_view_count"] = np.log1p(df["view_count"])
df["log_like_count"] = np.log1p(df["like_count"])
df["log_comment_count"] = np.log1p(df["comment_count"])
df["log_duration_seconds"] = np.log1p(df["duration_seconds"])

In [ ]:
# modelos não entendem data da mesma forma que nos, a grande maioria.
df["published_date"] = df["published_at"].dt.date
df["published_year"] = df["published_at"].dt.year
df["published_month"] = df["published_at"].dt.month
df["published_hour"] = df["published_at"].dt.hour
df["published_dayofweek"] = df["published_at"].dt.day_name()

# posso talvez aplicar algum coisa de carga cognitiva, tendo em mente
# que é um oversimplification das abstracoes para simples números...
df["title_len"] = df["title"].fillna("").str.len()
df["title_words"] = df["title"].fillna("").str.split().apply(len)

USELESS_FIELDS: list[str] = [
    "thumbnail",
    "source_file",
    "source_path",
    "collection_id",
    "tags",
    "duration",
    "published_at"
]
df = df.drop(columns=[f for f in USELESS_FIELDS if f in df.columns])
df.dtypes

In [ ]:

util.printf("# visão geral e estrutura do dataset")
util.printf("## amostra dos dados (primeiras 5 linhas)")
display(df.head())

display(Markdown("---"))

util.printf("##  rsumo estatístico (variáveis nméricas)")
display(df.describe()) 

if df.select_dtypes(include=['object']).shape[1] > 0:
    util.printf("## resumo estatístico (variáveis categóricas)")
    display(df.describe())

In [ ]:
# display(Markdown(f"\nshape final: {df.shape[0]} linhas x {df.shape[1]} colunas"))

# POS_BASE_DIR = Path("../data/processed")
# POS_BASE_DIR.mkdir(parents=True, exist_ok=True)

# timestamp: str = datetime.now().strftime("%Y%m%d_%H%M%S")
# file_name: str = f"processed_videos_{timestamp}.csv"
# caminho_final: Path = POS_BASE_DIR / file_name

# df.to_csv(caminho_final, index=False, sep=',', encoding='utf-8')

# display(Markdown(f"\nsalvo no caminho: {caminho_final}"))

In [ ]:

import src.core.plot_eda as plots_
import os
out = "plots_output"
os.makedirs(out, exist_ok=True)
plots_.plot_boxplots(df,               f"{out}/1_boxplots.png")
plots_.plot_histograms(df,             f"{out}/2_histogramas.png")
plots_.plot_category_pie(df,           f"{out}/3_pizza_categorias.png")
plots_.plot_views_by_category(df,      f"{out}/4_views_por_categoria.png")
plots_.plot_scatter_views_likes(df,    f"{out}/5_scatter_views_likes.png")
plots_.plot_correlation_heatmap(df,    f"{out}/6_heatmap_correlacao.png")
plots_.plot_publish_hour(df,           f"{out}/7_hora_publicacao.png")
plots_.plot_engagement_violin(df,      f"{out}/8_violin_engagement.png")
plots_.plot_dashboard(df,              f"{out}/9_dashboard.png")

In [ ]:
df_clean: pd.DataFrame = df.copy()
df.dtypes

In [ ]:
import numpy as np
import pandas as pd
from sklearn.base import clone
from sklearn.model_selection import GroupShuffleSplit, cross_val_score, GroupKFold
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

CATS: list[int] = [17, 20, 22, 23, 28]

df_clf = df_clean.copy()
df_clf = df_clf[df_clf["category_id"].isin(CATS)].copy()

df_clf["tags_text"] = df_clf["tags_list"].apply(
    lambda xs: " ".join(xs) if isinstance(xs, list) else ""
)
df_clf["title_text"] = df_clf["title"].fillna("")
df_clf["text_for_model"] = (df_clf["title_text"] + " " + df_clf["tags_text"]).str.strip()

df_clf = df_clf[df_clf["text_for_model"].str.len() > 0].copy()

TEXT_FEATURE = "text_for_model"

NUMERIC_FEATURES: list[str] = [c for c in [
    "duration_seconds",
    "tags_n",
    "title_len",
    "title_words",
    "published_year",
    "published_month",
    "log_comment_count",
    "engagement_rate",
    "log_like_count",
    "log_view_count",
] if c in df_clf.columns]

CATEGORICAL_FEATURES: list[str] = [c for c in [
    "country",
    "published_dayofweek",
] if c in df_clf.columns]

print(f"Numeric features ({len(NUMERIC_FEATURES)}):     {NUMERIC_FEATURES}")
print(f"Categorical features ({len(CATEGORICAL_FEATURES)}): {CATEGORICAL_FEATURES}")

all_features = [TEXT_FEATURE] + NUMERIC_FEATURES + CATEGORICAL_FEATURES
X = df_clf[all_features].copy()
y = df_clf["category_id"].copy()
groups = df_clf["channel_id"].copy()

for col in CATEGORICAL_FEATURES:
    X[col] = X[col].astype("object")

splitter = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(splitter.split(X, y, groups=groups))

X_train, X_test = X.iloc[train_idx].copy(), X.iloc[test_idx].copy()
y_train, y_test = y.iloc[train_idx].copy(), y.iloc[test_idx].copy()
groups_train    = groups.iloc[train_idx].copy()

print(f"\nTreino: {len(X_train):,} amostras | Teste: {len(X_test):,} amostras")
print(f"Canais únicos — treino: {groups_train.nunique()} | teste: {groups.iloc[test_idx].nunique()}")

def make_tfidf() -> TfidfVectorizer:
    return TfidfVectorizer(ngram_range=(1, 2), min_df=2, max_features=6_000)

def make_preprocessor(scaler) -> ColumnTransformer:
    return ColumnTransformer(
        transformers=[
            ("text", make_tfidf(), TEXT_FEATURE),
            ("num", Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", scaler),
            ]), NUMERIC_FEATURES),
            ("cat", Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
            ]), CATEGORICAL_FEATURES),
        ],
        remainder="drop",
    )

models: dict[str, Pipeline] = {
    "LogisticRegression": Pipeline([
        ("preprocessor", make_preprocessor(StandardScaler(with_mean=False))),
        ("clf", LogisticRegression(max_iter=5_000, solver="saga", class_weight="balanced")),
    ]),
    "LinearSVC": Pipeline([
        ("preprocessor", make_preprocessor(StandardScaler(with_mean=False))),
        ("clf", LinearSVC(class_weight="balanced", max_iter=5_000)),
    ]),
    "MultinomialNB": Pipeline([
        ("preprocessor", make_preprocessor(MinMaxScaler())),
        ("clf", MultinomialNB(alpha=0.5)),
    ]),
}

results = []

for name, model in models.items():
    print(f"\n{'='*60}")
    print(f"  {name}")
    print(f"{'='*60}")

    model.fit(X_train, y_train)
    pred = model.predict(X_test)

    acc        = accuracy_score(y_test, pred)
    f1_macro   = f1_score(y_test, pred, average="macro")
    f1_weighted = f1_score(y_test, pred, average="weighted")

    print(classification_report(y_test, pred))
    print("Confusion matrix:")
    print(confusion_matrix(y_test, pred))

    cv = GroupKFold(n_splits=3)
    cv_scores = cross_val_score(
        clone(model), X_train, y_train,
        groups=groups_train,
        cv=cv,
        scoring="f1_macro",
        n_jobs=-1,
    )
    print(f"\nCV f1_macro (3 folds): {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

    results.append({
        "model":        name,
        "accuracy":     acc,
        "f1_macro":     f1_macro,
        "f1_weighted":  f1_weighted,
        "cv_f1_mean":   cv_scores.mean(),
        "cv_f1_std":    cv_scores.std(),
    })

results_df = (
    pd.DataFrame(results)
    .sort_values("f1_macro", ascending=False)
    .reset_index(drop=True)
)
print("\n" + "="*60)
print("  Resumo dos modelos")
print("="*60)
print(results_df.to_string(index=False))

In [ ]:
import matplotlib.pyplot as plt

plot_df: pd.DataFrame = results_df.set_index("model")

plot_df[["accuracy", "f1_macro", "f1_weighted"]].plot(
    kind="bar",
    figsize=(10, 5)
)

plt.title("Comparação dos Modelos")
plt.ylabel("Score")
plt.ylim(0, 1)
plt.xticks(rotation=0)
plt.grid(axis="y", alpha=0.3)
plt.show()

In [ ]:
from sklearn.metrics import ConfusionMatrixDisplay

best_model = models["LinearSVC"]
pred = best_model.predict(X_test)

fig, ax = plt.subplots(figsize=(8, 8))

ConfusionMatrixDisplay.from_predictions(
    y_test,
    pred,
    ax=ax,
    cmap="Blues"
)

plt.title("Matriz de Confusão")
plt.show()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,4))

sns.countplot(
    data=df_clf,
    x="category_id",
    order=df_clf["category_id"].value_counts().index
)

plt.title("Distribuição das Categorias")
plt.show()

In [ ]:
svc = models["LinearSVC"]

# 1. Get feature names
feature_names = (
    svc.named_steps["preprocessor"]
       .get_feature_names_out()
)

coef = svc.named_steps["clf"].coef_
cat_idx = 0

top = coef[cat_idx].argsort()[-20:]

plt.figure(figsize=(8,5))
plt.barh(
    np.array(feature_names)[top],
    coef[cat_idx][top]
)
plt.title("Palavras mais importantes")
plt.show()

In [ ]:
import re
import emoji
from scipy.sparse import hstack
from scipy.sparse import csr_matrix

def clean_title(text):
    if pd.isna(text):
        return ""

    text = str(text)

    text = re.sub(r'\s+', ' ', text)

    return text.strip()

def extract_title_features(title):

    title = str(title)

    words = title.split()

    return {
        "title_len": len(title),
        "word_count": len(words),

        "uppercase_ratio":
            sum(c.isupper() for c in title) /
            max(len(title), 1),

        "digit_count":
            sum(c.isdigit() for c in title),

        "exclamation_count":
            title.count("!"),

        "question_count":
            title.count("?"),

        "ellipsis_count":
            title.count("..."),

        "emoji_count":
            len([c for c in title if c in emoji.EMOJI_DATA]),

        "has_hashtag":
            int("#" in title),

        "has_number":
            int(any(c.isdigit() for c in title)),

        "has_caps_word":
            int(any(
                len(w) > 2 and w.isupper()
                for w in words
            ))
    }
df["title"] = df["title"].apply(clean_title)

feature_df = pd.DataFrame(
    df["title"].apply(extract_title_features).tolist()
)

from sklearn.feature_extraction.text import TfidfVectorizer

word_tfidf = TfidfVectorizer(
    max_features=3000,
    ngram_range=(1,2),
    min_df=3
)

X_word = word_tfidf.fit_transform(df["title"])

char_tfidf = TfidfVectorizer(
    analyzer="char_wb",
    ngram_range=(3,5),
    max_features=2000
)

X_char = char_tfidf.fit_transform(df["title"])



X_numeric = csr_matrix(feature_df.values)

X = hstack([
    X_numeric,
    X_word,
    X_char
])

from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters=16,
    random_state=42
)

clusters = kmeans.fit_predict(X)

df["cluster"] = clusters

for c in sorted(df["cluster"].unique()):

    print(f"\n=== CLUSTER {c} ===")

    sample = df[df["cluster"] == c]["title"].head(10)

    for t in sample:
        print(t)

In [ ]:
import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer

from sklearn.preprocessing import Normalizer
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

# model = SentenceTransformer(
#     "paraphrase-multilingual-MiniLM-L12-v2"
# )
model = SentenceTransformer("intfloat/multilingual-e5-base")

import re


def limpeza_profunda(texto: str):    
    texto = texto.lower()
    texto = re.sub(r'#\w+', '', texto)
    texto = re.sub(r'https?://\s+|www\.\s+', '', texto)
    texto = re.sub(r'[^a-zA-Z0-9áéíóúâêôãõç\s]', '', texto)
    texto = " ".join(texto.split())
    
    return texto

df_clf["title_clean"] = df_clf["title"].apply(limpeza_profunda)

titles_para_treino = df_clf["title_clean"].tolist()
def limpar_titulo(texto):
    texto: str = re.sub(r'#\w+', '', texto)
    texto = re.sub(r'[^\w\s]', '', texto, flags=re.UNICODE)
    return " ".join(texto.split()).lower()

df_clf["clean_title"] = df_clf["title"].fillna("").astype(str).apply(limpar_titulo)
titles = df_clf["clean_title"].tolist()

embeddings = model.encode(
    titles,
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True
)

print("Embeddings:", embeddings.shape)


normalizer = Normalizer()

X_norm = normalizer.fit_transform(embeddings)

pca = PCA(
    n_components=50,
    random_state=42
)

X_reduced = pca.fit_transform(X_norm)

print("Após PCA:", X_reduced.shape)

kmeans = KMeans(
    n_clusters=10,
    random_state=42,
    n_init="auto"
)

clusters = kmeans.fit_predict(X_reduced)

df_clf["cluster"] = clusters


for cluster_id in sorted(df_clf["cluster"].unique()):

    print(f"\n{'='*50}")
    print(f"CLUSTER {cluster_id}")

    sample = (
        df_clf[df_clf["cluster"] == cluster_id]
        ["title"]
        .sample(
            min(
                10,
                (df_clf["cluster"] == cluster_id).sum()
            ),
            random_state=42
        )
    )

    for title in sample:
        print("-", title)

In [ ]:
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score

sil = silhouette_score(X_reduced, clusters, sample_size=2000, random_state=42)

db = davies_bouldin_score(X_reduced, clusters)

ch = calinski_harabasz_score(X_reduced, clusters)

print(f"Silhouette Score:        {sil:.4f}  (ideal → 1.0)")
print(f"Davies-Bouldin Score:    {db:.4f}  (ideal → 0.0)")
print(f"Calinski-Harabasz Score: {ch:.2f}  (ideal → ∞)")

In [ ]:
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score, homogeneity_completeness_v_measure

labels_reais = df_clf["category_id"].values

# ARI: -1 a +1, acima de 0.3 já é bom para clustering
ari = adjusted_rand_score(labels_reais, clusters)

# NMI: 0 a 1
nmi = normalized_mutual_info_score(labels_reais, clusters)


hom, comp, v = homogeneity_completeness_v_measure(labels_reais, clusters)

print(f"ARI:          {ari:.4f}")
print(f"NMI:          {nmi:.4f}")
print(f"Homogeneity:  {hom:.4f}")
print(f"Completeness: {comp:.4f}")
print(f"V-measure:    {v:.4f}")

In [ ]:
import matplotlib.pyplot as plt

inertias = []
sil_scores = []
k_range = range(3, 20)

for k in k_range:
    km = KMeans(n_clusters=k, random_state=42, n_init="auto")
    labels = km.fit_predict(X_reduced)
    inertias.append(km.inertia_)
    sil_scores.append(silhouette_score(X_reduced, labels, sample_size=2000, random_state=42))

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

ax1.plot(k_range, inertias, marker="o")
ax1.set_title("Elbow Method (Inércia)")
ax1.set_xlabel("n_clusters")
ax1.set_ylabel("Inércia")

ax2.plot(k_range, sil_scores, marker="o", color="orange")
ax2.set_title("Silhouette por k")
ax2.set_xlabel("n_clusters")
ax2.set_ylabel("Silhouette Score")

plt.tight_layout()
plt.show()