In [4]:
from typing import Any
from __future__ import annotations

from IPython.display import display, Markdown

import sys
from datetime import datetime, timezone
from pathlib import Path
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.gridspec as gridspec
import ast
import isodate
import pandas as pd
import numpy as np

ROOT: Path = Path.cwd().parent
sys.path.append(str(ROOT))

import src.core.util_examplification as examplification
BASE_DIR = Path("../data/raw")

PALETTE: dict[str, str] = {
    "bg": "#0D0F1A",
    "panel": "#141726",
    "accent1": "#FF4D6D",
    "accent2": "#4CC9F0",
    "accent3": "#F4A261",
    "accent4": "#2EC4B6",
    "text": "#E8EAF0",
    "muted": "#6C7293",
}

datasets: dict[str, list[Any]] = {
    "channels": [],
}

def printf(text_format):
    display(Markdown(text_format))
    
for csv_file in BASE_DIR.rglob("*.csv"):
    try:
        df = pd.read_csv(csv_file)

        df["source_file"] = csv_file.name
        df["source_path"] = str(csv_file)

        id_dir = next(
            (part for part in csv_file.parts if part.startswith("id_")),
            None
        )
        df["collection_id"] = id_dir

        stem_parts = csv_file.stem.split("_")
        country: str = stem_parts[-1] if len(stem_parts) > 2 else None
        df["country"] = country

        filename = csv_file.name.lower()

        if "channel" in filename:
            datasets["channels"].append(df)

    except Exception as e:
        print(f"Erro ao ler {csv_file}: {e}")

channels_df = pd.concat(datasets["channels"], ignore_index=True) \
    if datasets["channels"] else pd.DataFrame()

display(f"Channels: {len(channels_df)}")

'Channels: 1129'

In [5]:

printf("# visão geral e estrutura do dataset")
printf("## amostra dos dados (primeiras 5 linhas)")
display(channels_df.head())

display(Markdown("---"))

printf("##  rsumo estatístico (variáveis nméricas)")
display(channels_df.describe()) 

if channels_df.select_dtypes(include=['object']).shape[1] > 0:
    printf("## resumo estatístico (variáveis categóricas)")
    display(channels_df.describe())

# visão geral e estrutura do dataset

## amostra dos dados (primeiras 5 linhas)

,channel_id,title,description,custom_url,published_at,country,thumbnail,view_count,subscriber_count,video_count,hidden_subscriber_count,source_file,source_path,collection_id
0,UC40B1IOUytiN6AmnlR3BRaw,Xey,Canal focado em conteúdo para crianças e adole...,@xey,2019-10-24T22:45:33.959053Z,br,https://yt3.ggpht.com/Wh_ca7OcF9dt_M19WB_vhfcG...,250401388,1980000,2044,False,youtube_channels_br.csv,../data/raw/output_160902062026/id_20/youtube_...,id_20
1,UCYtaoJSk9iIrFxx8eZB15ag,Robin Hood Gamer,Robin Hood ao lado de Beto e HeyDavi vive nova...,@robinhoodgamer1,2014-05-17T19:10:37Z,br,https://yt3.ggpht.com/MMCzsxb_Q7OcqeL-4msKIdY-...,12017826418,22500000,4627,False,youtube_channels_br.csv,../data/raw/output_160902062026/id_20/youtube_...,id_20
2,UCSp81o_5gs9sMExB3Ij0p-w,Berg Tv,"Olá, você está no canal Berg Tv!\n\nE-mail par...",@bergtv,2016-02-01T19:20:19Z,br,https://yt3.ggpht.com/FthmtVavyQkmFHhWp7bIAPp-...,493210557,2500000,597,False,youtube_channels_br.csv,../data/raw/output_160902062026/id_20/youtube_...,id_20
3,UC3gPyQUYIoes61GCO7dah_Q,Smurfzin,Já ajeitou a coluna hoje? ☕💙\n,@smurfzin,2016-06-05T21:44:48Z,br,https://yt3.ggpht.com/tf525HRMWBoBFxpGr1M5e3mG...,414181209,2180000,1059,False,youtube_channels_br.csv,../data/raw/output_160902062026/id_20/youtube_...,id_20
4,UCYkjBwZBgKTPuTLf_o4qcqw,ALEC GO! #games,🤪 BEM VINDOS AO CANAL ALEC GO! 🕹️\n\nEU ME CHA...,@alecgogames,2021-05-05T17:44:33.186437Z,br,https://yt3.ggpht.com/Yd8soh5yHBjSWvly4PlCaY-T...,597580645,1680000,705,False,youtube_channels_br.csv,../data/raw/output_160902062026/id_20/youtube_...,id_20

---

##  rsumo estatístico (variáveis nméricas)

         view_count  subscriber_count   video_count
count  1.129000e+03      1.129000e+03   1129.000000
mean   1.534514e+09      3.032611e+06   1846.109832
std    3.842220e+09      7.038522e+06   4323.292342
min    1.213860e+05      1.000000e+04      4.000000
25%    6.047443e+07      1.360000e+05    271.000000
50%    2.735955e+08      6.400000e+05    792.000000
75%    1.081879e+09      2.650000e+06   1955.000000
max    5.497983e+10      7.220000e+07  66678.000000

/tmp/ipykernel_23072/3457841217.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  if channels_df.select_dtypes(include=['object']).shape[1] > 0:

## resumo estatístico (variáveis categóricas)

         view_count  subscriber_count   video_count
count  1.129000e+03      1.129000e+03   1129.000000
mean   1.534514e+09      3.032611e+06   1846.109832
std    3.842220e+09      7.038522e+06   4323.292342
min    1.213860e+05      1.000000e+04      4.000000
25%    6.047443e+07      1.360000e+05    271.000000
50%    2.735955e+08      6.400000e+05    792.000000
75%    1.081879e+09      2.650000e+06   1955.000000
max    5.497983e+10      7.220000e+07  66678.000000

In [7]:
channels_df

,channel_id,title,description,custom_url,published_at,country,thumbnail,view_count,subscriber_count,video_count,hidden_subscriber_count,source_file,source_path,collection_id
0,UC40B1IOUytiN6AmnlR3BRaw,Xey,Canal focado em conteúdo para crianças e adole...,@xey,2019-10-24T22:45:33.959053Z,br,https://yt3.ggpht.com/Wh_ca7OcF9dt_M19WB_vhfcG...,250401388,1980000,2044,False,youtube_channels_br.csv,../data/raw/output_160902062026/id_20/youtube_...,id_20
1,UCYtaoJSk9iIrFxx8eZB15ag,Robin Hood Gamer,Robin Hood ao lado de Beto e HeyDavi vive nova...,@robinhoodgamer1,2014-05-17T19:10:37Z,br,https://yt3.ggpht.com/MMCzsxb_Q7OcqeL-4msKIdY-...,12017826418,22500000,4627,False,youtube_channels_br.csv,../data/raw/output_160902062026/id_20/youtube_...,id_20
2,UCSp81o_5gs9sMExB3Ij0p-w,Berg Tv,"Olá, você está no canal Berg Tv!\n\nE-mail par...",@bergtv,2016-02-01T19:20:19Z,br,https://yt3.ggpht.com/FthmtVavyQkmFHhWp7bIAPp-...,493210557,2500000,597,False,youtube_channels_br.csv,../data/raw/output_160902062026/id_20/youtube_...,id_20
3,UC3gPyQUYIoes61GCO7dah_Q,Smurfzin,Já ajeitou a coluna hoje? ☕💙\n,@smurfzin,2016-06-05T21:44:48Z,br,https://yt3.ggpht.com/tf525HRMWBoBFxpGr1M5e3mG...,414181209,2180000,1059,False,youtube_channels_br.csv,../data/raw/output_160902062026/id_20/youtube_...,id_20
4,UCYkjBwZBgKTPuTLf_o4qcqw,ALEC GO! #games,🤪 BEM VINDOS AO CANAL ALEC GO! 🕹️\n\nEU ME CHA...,@alecgogames,2021-05-05T17:44:33.186437Z,br,https://yt3.ggpht.com/Yd8soh5yHBjSWvly4PlCaY-T...,597580645,1680000,705,False,youtube_channels_br.csv,../data/raw/output_160902062026/id_20/youtube_...,id_20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1124,UCs225CSfSuGmyADgQaXBoLQ,BeatboxTomi,1 million,@beatbox-tomi,2022-08-29T00:16:16.244952Z,br,https://yt3.ggpht.com/uEAfZx9TxRZhySG38NRoEFiZ...,35557367,300000,167,False,youtube_channels_br.csv,../data/raw/output_020620261628/id_28/youtube_...,id_28
1125,UCCOrp7GPgZA8EGrbOcIAsyQ,Phone Repair Guru,⬇️Products/Repair Tools/ Merch⬇️\nI do phone s...,@phonerepairguru,2013-04-09T23:50:18Z,br,https://yt3.ggpht.com/fONlaJBmPJOK2GtysqwNPk0u...,5443221737,5920000,1674,False,youtube_channels_br.csv,../data/raw/output_020620261628/id_28/youtube_...,id_28
1126,UCgj8hZkTZ2ryTbpA1QqpqMg,Eletrocutando Manutenção,Bem vindo ao canal Eletrocutando.\n\nO Foco pr...,@eletrocutando,2014-11-22T18:34:42Z,br,https://yt3.ggpht.com/ytc/AIdro_m0Dlz-QIF7QHiq...,3967543,14600,507,False,youtube_channels_br.csv,../data/raw/output_020620261628/id_28/youtube_...,id_28
1127,UCT0vEA-FQJtGveHAqauebFA,zoltrix,Hi my youtube family support me 🙏🙏🙏\njbl buffe...,@zoltrix-t6u,2025-07-19T13:46:29.872188Z,br,https://yt3.ggpht.com/37X1oY006K3tCtERgwlL0cgg...,82703599,20100,280,False,youtube_channels_br.csv,../data/raw/output_020620261628/id_28/youtube_...,id_28
1128,UCGmuLwV0XD_uqL4wKZg4hgA,Immersed,This is the official YouTube channel for Immer...,@immersedxr,2016-08-10T21:28:28Z,br,https://yt3.ggpht.com/ytc/AIdro_l16W0fA7YCJ0W9...,603764606,1600000,432,False,youtube_channels_br.csv,../data/raw/output_020620261628/id_28/youtube_...,id_28